### ISSUE TITLE
docs does not match with prop typechecking

### ISSUE THREAD

**Issue by Theadd** [rcdexta/react-event-timeline#1]
[TimelineEvent.js#L48-L49](https://github.com/rcdexta/react-event-timeline/blob/master/components/TimelineEvent.js#L48-L49)

``` js
  title: React.PropTypes.string.isRequired,
  createdAt: React.PropTypes.string.isRequired,
```

| Name | Type | Description |
| --- | --- | --- |
| title | node | The title of the event. **Can be string or any DOM element node(s)** |
| createdAt | node | The time at which the event occurred. **Can be datetime string or any DOM element node(s)** |

Thank you.

**Comment by rcdexta** [comment]
Fixed: https://github.com/rcdexta/react-event-timeline/commit/b194ac2a7536d70222886c3fcce220149b9937c2

Thanks for pointing it out
