### ISSUE TITLE
containerStyle (style prop) not being applied

### ISSUE THREAD

**Issue by smeijer** [rcdexta/react-event-timeline#10]
The `style` property (containerStyle) is only being applied when the `TimelineEvent` is being displayed as card. I like to use it to add some margin between my events. So this behavior feels wrong.

https://github.com/rcdexta/react-event-timeline/blob/master/components/TimelineEvent.js#L28

![image](https://user-images.githubusercontent.com/1196524/27706045-4a4719ea-5d10-11e7-8a38-12902e8b5a85.png)

**Comment by rcdexta** [comment]
Thanks for pointing this out. Fixed!

![screen shot 2017-07-05 at 16 31 22](https://user-images.githubusercontent.com/900028/27861683-6e565bc8-619f-11e7-880d-6feda3ab97cb.png)
