### ISSUE TITLE
Styling the card view

### ISSUE THREAD

**Issue by hashwin** [rcdexta/react-event-timeline#11]
Hi, nice project.

I would like to style the card header, looks like it is hardcoded into here:
https://github.com/rcdexta/react-event-timeline/blob/master/components/TimelineEvent.js#L43

Would be nice to have a new prop to be able to style this.

Thanks!

**Comment by rcdexta** [comment]
It's possible to override the card container's style by using the `style` prop. Have added more examples to the storybook: https://rcdexta.github.io/react-event-timeline/?selectedKind=Timeline&selectedStory=Card%20Appearance&full=0&down=0&left=1&panelRight=0

**Comment by hashwin** [comment]
Hi @rcdexta , this still does not allow me to style the color of the card header.

**Comment by rcdexta** [comment]
@hashwin there you go: https://rcdexta.github.io/react-event-timeline/?selectedKind=Timeline&selectedStory=Card%20Appearance&full=0&down=0&left=1&panelRight=0

**Comment by hashwin** [comment]
Awesome! 👍  Much appreciated
