### ISSUE TITLE
rtl

### ISSUE THREAD

**Issue by fereshtehaboohamzeh** [rcdexta/react-event-timeline#12]
is it working properly for rtl apps?

**Comment by rcdexta** [comment]
Interesting question. It should be possible to flip the styles using something like https://github.com/cssjanus/cssjanus to override existing css to support RTL. 

If you face any issues, pls provide more details with a sample code snippet of what you are trying to do and I can help. Thanks

**Comment by rcdexta** [comment]
Closing this issue for now...
