### ISSUE TITLE
TimelineEvent: iconStyle not working

### ISSUE THREAD

**Issue by MuratDavengo** [rcdexta/react-event-timeline#13]
Hello, the property `iconStyle` in TimelineEvent does not work. You forgot to include the spread operator. It worked in earlier versions. See here

https://github.com/rcdexta/react-event-timeline/commit/d4081a79167cf0cb3327c32e8ce36d522e8dc7d5#diff-625e8e59f6c96f4ff7ffa9978e9abb73R31

**Comment by rcdexta** [comment]
My bad. Fixed it now!
