### ISSUE TITLE
TimelineEvent: Allow style props for notification bubble

### ISSUE THREAD

**Issue by MuratDavengo** [rcdexta/react-event-timeline#14]
Hello, right now it's only allowed to pass the `iconColor` for the bubble. It might be a better idea to allow a whole style object similar to `iconStyle`.

https://github.com/rcdexta/react-event-timeline/blob/master/components/TimelineEvent.js#L6-L8

**Comment by rcdexta** [comment]
`iconStyle` is actually styling for the whole bubble. Now that iconStyle works, i have added an example as to what can be done:

https://rcdexta.github.io/react-event-timeline/?selectedKind=Timeline&selectedStory=Icon%20Styling&full=0&down=0&left=1&panelRight=0

Let me know if this works for you..
