### ISSUE TITLE
React 16 Support

### ISSUE THREAD

**Issue by aogaili** [rcdexta/react-event-timeline#15]
An older version of React is being loaded as a dependency:
 
https://github.com/rcdexta/react-event-timeline/blob/31c91670c26322e03ba42b9b4cc267e3222be8c3/package.json#L79-L82

I think it should be loaded as per dependency.

**Comment by rcdexta** [comment]
Will fix it this weekend. Thanks for pointing out.

**Comment by aogaili** [comment]
Thank you!

**Comment by rcdexta** [comment]
Upgraded to React 16 now. If your parent application uses React 15.x, this should work too.. Please pull v1.3.5

**Comment by rcdexta** [comment]
`react` and `react-dom` are peer dependencies now.. @aliogaili: Let me know if this works for you..

**Comment by aogaili** [comment]
Thanks @rcdexta  it's working great now. 

Just quick question, I noticed that the package.json doesn't have a version attribute.  I'm assuming you're using tags to publish. Is there a reason behind this choice? because it's the first time I see this and do you've some resources where I learn more about it. 

Thanks again for closing this issue.

**Comment by rcdexta** [comment]
I use semantic versioning workflow to take care of version bumping based on whether it is a feature/fix being committed and you can look here for more info: https://github.com/semantic-release/semantic-release

**Comment by aogaili** [comment]
Much appreciated, thanks @rcdexta

**Comment by aogaili** [comment]
Wow this semantic versioning is amazing, the node ecosystem keep on surprising me everyday, lots of smart folks around :)
