### ISSUE TITLE
Icon in TimelineEvent can't be centered

### ISSUE THREAD

**Issue by ChristianAEDev** [rcdexta/react-event-timeline#16]
First of all: Thanks for this great component!

I am facing a problem centering the icon of a TimelineEvent. (I am using [Material-UI](https://material-ui-1dab0.firebaseapp.com).)

It currently looks like this:
![image](https://user-images.githubusercontent.com/10501258/31854402-49ff987a-b690-11e7-8ac2-7b4f61187362.png)

I found issues #7 after which you introduced `iconStyle`. I am using the following code:
```
import PhoneIcon from 'material-ui-icons/PermPhoneMsg';

[...]
            <TimelineEvent
              title={update.title}
              createdAt={moment(update.timestamp).format(DATE_TIME_FORMAT)}
              icon={<PhoneIcon />}
              iconStyle={{ marginLeft: 0, marginTop: 0 }}
              iconColor="#5C6BC0"
            >
              {update.description}
            </TimelineEvent>
[...]
```
It seems that `iconStyle` is changing the style of the complete Icon, but not the actual icon enclosed.

If I change the value to `iconStyle={{ marginLeft: 20, marginTop: 20 }}` it looks like this:
![image](https://user-images.githubusercontent.com/10501258/31854421-bfbde332-b690-11e7-9961-ce89ce42cc79.png)
What I want to achieve is to move the phone icon within the TimelineEvent icon.

I am fairly new to React (Java developer here ;) therefore I hope I don't miss anything obvious.

Kind regards

**Comment by rcdexta** [comment]
ok 2 things to address the issue that you are facing:

1. The logic to center the icon inside the bubble was font size dependent. Now, the patch should make the icon centered inside the bubble agnostic of the material icon size you prefer
2. Added another prop called `bubbleStyle` to customize the look-and-feel of the bubble. You can use `iconStyle` prop to alter the styling of the specific icon enclosed within the bubble now.

Example here: https://rcdexta.github.io/react-event-timeline/?selectedKind=Timeline&selectedStory=Icon%20and%20Bubble%20Styling&full=0&down=0&left=1&panelRight=0

Please pull the latest release for the patch. Thanks for using the library!

**Comment by ChristianAEDev** [comment]
Perfect! Works exactly as I want.

Thank's for also providing a storybook. Makes working with the component a lot easier.
