### ISSUE TITLE
'iconStyle' and 'style' properties not working for TimelineBlip

### ISSUE THREAD

**Issue by derek-groupmail** [rcdexta/react-event-timeline#18]
This is probably related to issue #13 and presumably has a similar fix.

I've found that iconStyle does indeed now work for TimelineEvents but the exact same property applied to TimelineBlips doesn't appear to append the css content to the icon styling.

Similarly, I've found that the 'style' property works for TimelineEvents but not for TimelineBlips.

**Comment by rcdexta** [comment]
v1.4.2 should fix it.. Story snippet with example:

https://rcdexta.github.io/react-event-timeline/?selectedKind=Timeline&selectedStory=Condensed%20Timeline&full=0&down=0&left=1&panelRight=0
