### ISSUE TITLE
Add event listeners to `TimelineEvent` component

### ISSUE THREAD

**Issue by sureshHARDIYA** [rcdexta/react-event-timeline#2]
I am using your package to implement timeline in my project. Works great. Furthermore, I want to pass some event listeners to `TimelineEvent` component like:

```
<TimelineEvent
          createdAt="2016-09-11 09:06 AM"
          icon={<i className="uk-icon-envelope uk-icon-small" />}
          iconColor="#03a9f4"
          title="Added payment method."
          onClick={handleCollapse}
          onHover={handleHover}
 >
```
Currently, it does not seem to have these props, are you planning to add these or any way I can workaround? All I want is to fire some event, when user clicks on the `TimelineEvent` title or hovers over it. Thanks in advance.

**Comment by rcdexta** [comment]
Thanks for trying out the library. This commit https://github.com/rcdexta/react-event-timeline/commit/e5cf1a237b425e7bd18b9d5fdd49616906400d73 should address your issue. Also have added an example to [Storybook](https://rcdexta.github.io/react-event-timeline/?selectedKind=Timeline&selectedStory=Event%20handlers&full=0&down=1&left=1&panelRight=0) for your reference. Please pull the latest package from npm
