### ISSUE TITLE
Collapsible not working

### ISSUE THREAD

**Issue by Arrefelt** [rcdexta/react-event-timeline#28]
Want to use the neat collapse feature which I saw is pretty new, however it does not work as it seems the property is not recognized. Copying the code from your storybook:

https://rcdexta.me/react-event-timeline/?selectedKind=Timeline&selectedStory=TimelineEvent%20with%20collapsible%20content&full=0&down=0&left=1&panelRight=0

gives me error:

Warning: Received `true` for a non-boolean attribute `collapsible`.
If you want to write it to the DOM, pass a string instead: collapsible="true" or collapsible={value.toString()}.

Using version 1.5.4. I noticed that the merge of that feature to master gave a compile error so that's probably why?

**Comment by rcdexta** [comment]
@Arrefelt Thanks for pointing this out. This is fixed in the latest release v1.6.0
