### ISSUE TITLE
Warning: Unknown prop `container` on <div> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by technotronic12** [rcdexta/react-event-timeline#4]
When using the timeline event like this:
```
      <TimelineEvent
      title={title}
      createdAt={moment(event.dateTime).format('MMMM Do, h:mm:ss a')}
      container="card"
      icon={icon}
      iconColor={iconColor}
      contentStyle={{display: show}}
      key={`event#${index}`}
      className={styles.incidentTimeLineEvent}
      >
```
I get this warning:

> Warning: Unknown prop `container` on < div > tag. Remove this prop from the element.

**Comment by rcdexta** [comment]
@technotronic12 Thanks for pointing this out. Fixed in the latest build.

Reference: https://rcdexta.github.io/react-event-timeline/?selectedKind=Timeline&selectedStory=Card%20Appearance&full=0&down=0&left=1&panelRight=0

**Comment by technotronic12** [comment]
Thanks!
