### ISSUE TITLE
Dynamically update createdAt after every cycle.

### ISSUE THREAD

**Issue by oztek22** [rcdexta/react-event-timeline#5]
I want to display createdAt time in "time ago" format which is updated after every 5 seconds.
I've created function to display time in that format now 
![cc](https://cloud.githubusercontent.com/assets/14314089/26058695/91d3b77e-399c-11e7-8904-468a6be87301.PNG)
how can I dynamically update the display.I change value of var which display 0 sec ago after every 10 sec but it's not updating the view.
ps:please excuse the content of feed 😆

**Comment by rcdexta** [comment]
It should be possible to dynamically update the created at field periodically. Created a new story to illustrate that: 

https://rcdexta.github.io/react-event-timeline/?selectedKind=Timeline&selectedStory=Dynamic%20Prop%20Updates&full=0&down=0&left=1&panelRight=0

The code is available here: https://github.com/rcdexta/react-event-timeline/blob/master/stories/App.story.js#L111

![rt](https://cloud.githubusercontent.com/assets/900028/26147778/3572a0b8-3b12-11e7-9dca-f6cfafb2359c.gif)

**Comment by smeijer** [comment]
@oztek22, your screenshot looks awesome. Did you create it with this library? Do you have a code-sample on how to create it like that?

**Comment by rcdexta** [comment]
@smeijer Used this https://giphy.com/apps/giphycapture to create the gif

**Comment by oztek22** [comment]
@smeijer sorry for late response.
 I've created function to calculate timeAgo and passed it into timeline in created at.

**Comment by oztek22** [comment]
thanks @rcdexta for this awesome library.
that thing solved my issue.
