### ISSUE TITLE
Children shouldn't be required

### ISSUE THREAD

**Issue by smeijer** [rcdexta/react-event-timeline#8]
Sometimes I just want a title and that's it. A body is not always wanted. 

Look for example at a github timeline:

![image](https://user-images.githubusercontent.com/1196524/27703274-1c09d170-5d07-11e7-93af-319d52a560aa.png)

**Comment by rcdexta** [comment]
@smeijer Thanks for the suggestion. Makes sense. v1.2.5 incorporates this change
