### ISSUE TITLE
rename createdAt to subtitle

### ISSUE THREAD

**Issue by smeijer** [rcdexta/react-event-timeline#9]
I think it's better to have a `title` and a `subtitle` to keep the terms more generic. This because there isn't anything special happening with the `createdAt` anyway. It's just a `node`, just like `title`, `icon` and `children`.

So, I guess it's better to rename `title` to `subtitle` and `createdAt` to `title` (because a `subtitle` should be standing below the `title`).

**Comment by rcdexta** [comment]
TimelineEvent is precisely for displaying time related events and hence the rationale to have `createdAt` as an attribute. For the need that you mentioned, I created a new type of Timeline component called `TimelineBlip`. This is used to display events that can be contained within a single line.

See here for example: https://rcdexta.github.io/react-event-timeline/?selectedKind=Timeline&selectedStory=Condensed%20Timeline&full=0&down=0&left=1&panelRight=0

We can think about having `title` and `subtitle` attributes for this new component if needed

**Comment by smeijer** [comment]
True, it is a timeline indeed. But the case is; when i want the date below the title, I currently need to set the title in `createdAt` and the date in `title`. That feels strange at least.

The blip is looking awesome 😄

**Comment by rcdexta** [comment]
I hear you :) I can see if i can pseudo aliases to properties for your use case. Will keep you posted!

**Comment by rcdexta** [comment]
Added `title` and `subtitle` props along with `titleStyle` and `subtitleStyle` to override styling. 

Example usage here: https://rcdexta.github.io/react-event-timeline/?selectedKind=Timeline&selectedStory=Title%20and%20Subtitle%20styling&full=0&down=0&left=1&panelRight=0
